services:
  app:
    image: ${DOCKER_USERNAME}/unisoul:${IMAGE_TAG:-latest}
    container_name: unisoul-app
    build: !reset null
    labels:
      - "app=unisoul"
    ports:
      - "${APP_PORT:-8050}:80"
    volumes: !reset []
    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      resources:
        limits:
          memory: 700M
        reservations:
          memory: 256M
    environment:
      - APP_NAME=${APP_NAME}
      - APP_ENV=${APP_ENV:-production}
      - APP_KEY=${APP_KEY}
      - APP_DEBUG=${APP_DEBUG:-false}
      - APP_URL=${APP_URL}
      - APP_LOCALE=${APP_LOCALE:-en}
      - APP_FALLBACK_LOCALE=${APP_FALLBACK_LOCALE:-en}
      - LOG_CHANNEL=${LOG_CHANNEL:-stack}
      - LOG_STACK=${LOG_STACK:-daily}
      - LOG_LEVEL=${LOG_LEVEL:-warning}
      - DB_CONNECTION=${DB_CONNECTION:-mysql}
      - DB_HOST=${DB_HOST:-host.docker.internal}
      - DB_PORT=${DB_PORT:-3306}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - SESSION_DRIVER=${SESSION_DRIVER:-database}
      - SESSION_LIFETIME=${SESSION_LIFETIME:-120}
      - CACHE_STORE=${CACHE_STORE:-redis}
      - QUEUE_CONNECTION=${QUEUE_CONNECTION:-redis}
      - REDIS_HOST=${REDIS_HOST:-host.docker.internal}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - MAIL_MAILER=${MAIL_MAILER}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_FROM_ADDRESS=${MAIL_FROM_ADDRESS}
      - MAIL_FROM_NAME=${MAIL_FROM_NAME}
      - MODEL_SETTINGS_PERSISTENT=${MODEL_SETTINGS_PERSISTENT:-true}
      - SUPPORTED_LANGUAGES=${SUPPORTED_LANGUAGES:-uk,en,ro,de,ka}
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - OWNER_ID=${OWNER_ID}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - unisoul-network

networks:
  unisoul-network:
    driver: bridge
